import type { MockBook } from "@/types/route-builder";

export const MOCK_BOOKS: MockBook[] = [
  {
    id: "b1",
    title: "システム英単語",
    subject: "英語",
    coverImageUrl: null,
    level: "standard",
  },
  {
    id: "b2",
    title: "ターゲット1900",
    subject: "英語",
    coverImageUrl: null,
    level: "standard",
  },
  {
    id: "b3",
    title: "Next Stage 英文法",
    subject: "英語",
    coverImageUrl: null,
    level: "standard",
  },
  {
    id: "b4",
    title: "英文解釈の技術100",
    subject: "英語",
    coverImageUrl: null,
    level: "advanced",
  },
  {
    id: "b5",
    title: "青チャート 数学IA",
    subject: "数学",
    coverImageUrl: null,
    level: "standard",
  },
  {
    id: "b6",
    title: "青チャート 数学IIB",
    subject: "数学",
    coverImageUrl: null,
    level: "standard",
  },
  {
    id: "b7",
    title: "数学 基礎問題精講 IA",
    subject: "数学",
    coverImageUrl: null,
    level: "basic",
  },
  {
    id: "b8",
    title: "物理のエッセンス 力学・波動",
    subject: "物理",
    coverImageUrl: null,
    level: "standard",
  },
  {
    id: "b9",
    title: "化学の新研究",
    subject: "化学",
    coverImageUrl: null,
    level: "advanced",
  },
  {
    id: "b10",
    title: "現代文読解力の開発講座",
    subject: "国語",
    coverImageUrl: null,
    level: "standard",
  },
  {
    id: "b11",
    title: "古文単語ゴロゴ",
    subject: "国語",
    coverImageUrl: null,
    level: "basic",
  },
  {
    id: "b12",
    title: "日本史B 一問一答",
    subject: "社会",
    coverImageUrl: null,
    level: "standard",
  },
];
